version = 3.8.3
runner.dialect = scala3
maxColumn = 120

rewrite.scala3.convertToNewSyntax = true
rewrite.trailingCommas.style = always
docstrings.style = Asterisk
preset = default
indent.defnSite = 2
optIn.configStyleArguments = false
align.preset = none
indent.extendSite = 2
indent.withSiteRelativeToExtends = 2